export default {
    name: 'clientWork',
    title: 'Client Work',
    type: 'document',
    fields: [
        { name: 'title', title: 'Title', type: 'string', validation: (Rule) => Rule.required() },
        { name: 'role', title: 'Role', type: 'string' },
        { name: 'type', title: 'Type', type: 'string' },
        { name: 'badge', title: 'Badge', type: 'string' },
        { name: 'badgeColor', title: 'Badge Color', type: 'string', options: { list: [{ title: 'Emerald', value: 'emerald' }, { title: 'Blue', value: 'blue' }] } },
        { name: 'description', title: 'Description', type: 'text' },
        { name: 'tech', title: 'Technologies', type: 'array', of: [{ type: 'string' }] },
        { name: 'color', title: 'Gradient Color', type: 'string' },
        { name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] },
        { name: 'link', title: 'Live Link', type: 'url' },
        { name: 'linkLabel', title: 'Link Label', type: 'string' },
        {
            name: 'caseStudy',
            title: 'Case Study',
            type: 'object',
            fields: [
                { name: 'client', title: 'Client', type: 'string' },
                { name: 'role', title: 'Role', type: 'string' },
                { name: 'challenge', title: 'Challenge', type: 'text' },
                { name: 'delivered', title: 'Delivered', type: 'text' },
                { name: 'stack', title: 'Stack', type: 'string' },
                { name: 'result', title: 'Result', type: 'text' },
                { name: 'next', title: 'Next', type: 'text' },
            ],
        },
        { name: 'order', title: 'Order', type: 'number' },
    ],
    orderings: [{ title: 'Order', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] }],
};
